FROM php:7.4-cli-alpine

#RUN apk update
#RUN apk add zip unzip gnupg curl sudo cron

#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www

#COPY ./docker/runner/scripts/* /usr/local/bin/
#COPY ./docker/runner/xdebug.ini /etc/php/7.4/mods-available/

